# Site settings
title: Shreyas N B
email: shreyasnb@iitb.ac.in
description: Academic webpage of Shreyas Bharadwaj
baseurl: ""
url: ""
affiliation: I am a student in the <a href="http://aero.iitb.ac.in/" target="_blank">Aerospace Engineering Department</a> at the Indian Institute of Technology Bombay.

# Google analytics ID
# google_analytics: UA-176412042-1

# Location info. (shown in footer)
location: >
  Indian Institute of Technology Bombay<br/>
  Main Gate Rd<br/>
  Powai, MH 400076<br/>

# Contact info. (shown in footer)
contact: >
    Contact me via email: <a href="mailto:shreyasnb@gmail.com" target="_blank">snb.iitb@gmail.com</a> <br/>
    <br/><a href="https://github.com/shreyasnb/shreyasnb.github.io">Use this webpage as a template for your own!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: blurbs
  - name: CV
# - name: research
# - name: software
# - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
